### ISSUE TITLE
Uppercase Greek letters with leftside diacritics: diacritics outside container, diappearance of diacritics and of whitespace

### ISSUE THREAD

**Issue by Laisvunas** [rosettatype/eczar#21]
Hi,

I found a bug related to display of almost all of uppercase Greek letters with leftside diacritics.

There are several related issues concerning display of these letters.

1. Leftside diacritics of uppercase Greek letters are displayed outside container if they stand on the left side of the HTML container such as <div> element.

2. CSS rule 'overflow-y: scroll' applied to container forces leftside diacritics of uppercase letters to diappear.

3. Leftside diacritics of uppercase Greek letters forces the space between words to disappear. In simple case the CSS rule "text-rendering: optimizelegibility" can solve this issue, but this rule does not help in other simple cases.

4. Simple case when CSS rule "text-rendering: optimizelegibility" cannot solve diasappearance of whitespace is wrapping the word with <span></span> tags.

Testcase HTML page attached (change the file extension). 

Eczar is most beautiful and most readable font supporrting Greek extended char range. But unfortunately this issue makes it essentially unusable for Greek.

Thank you four your amazing achievement. Your work is really appreciated.

[testcase.txt](https://github.com/rosettatype/eczar/files/2345804/testcase.txt)

**Comment by MrBrezina** [comment]
Hi,

I think the Greek version of Eczar is hosted somewhere else.

@davelab6 How did you put it together in the end?

**Comment by Laisvunas** [comment]
Hi David,

I posted in the wrong place. Thanks for pointing that.

Trying to be relevant: I checked Skolar font, which you created and which seems to be based on Eczar, and found that the issue I reported on  Greek version Eczar  is fully reproduceable in Skolar (just change font-family name from Eczar to Skolar in testcase file).

Identical issue most probably needs needs identical fix. So, maybe you could fix both Skolar font and Eczar font with Greek letters from https://github.com/eellak/gsoc17-Eczar ?

**Comment by MrBrezina** [comment]
Just to be clear, Skolar is several years older than Eczar. :)

**Comment by davelab6** [comment]
I didn't. Yet. I have a project in my plan for you to do it as we discussed, I guess I should get that kicked off.

**Comment by MrBrezina** [comment]
@Laisvunas 

Re 1.: that is the inteded behaviour
Re 2.: seems like a bug in whatever browser you are using. I am not an expert in CSS, so I might be misunderstanding, but glyphs reaching out of their advance width is pretty common.
Re 3: yes, that is a problem if you have kerning switched off. Having kerning switch off is a bad typographic practice. Keep it on! :)
Re 4: that is a very good point! That is if you are saying that when glyphs (e.g. word space with the following word) that need to be kerned are in different tags and you cannot kern across tag boundaries, there is a problem.

There are basically two approaches to dealing with diacritics on Greek caps. The one used by Skolar and Eczar is to push them out of the “boxes” of the base glyphs. Another one is to add space. That has a problem if having an uneven alignment of text block on the left side (because you cannot kern letters with edge of a block). This seems to be acceptable to many, but might not be the option the original type designer preferred. Other possible solutions are not well supported by the text layout engines AFAIK.

Hope this helps.
